name: release-mingw
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        
jobs:
  mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\msys64\msys2_shell.cmd -mingw64 -defterm -no-start -here -c ". <(cygpath '{0}')"
        working-directory: ./pkg/urbit

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      # echo suppresses pacman prompt
      - run: echo|./configure
        env:
          CACHIX_CACHE: locpyl-tidnyd-test1
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: make build/urbit build/urbit-worker
      - run: build/urbit -l -d -B ../../bin/solid.pill -F bus && curl -f --data '{"source":{"dojo":"+hood/exit"},"sink":{"app":"hood"}}' http://localhost:12321
      - uses: actions/upload-artifact@v2
        with:
          name: mingw-build
          path: ./pkg/urbit/build/*.exe
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: mingw
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: mingw-build
          commit: mingw-port-release
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
